### ISSUE TITLE
Start at 12 o'clock

### ISSUE THREAD

**Issue by ghost** [camjc/elm-chart#1]
I'd like to be able to make my pie charts start at the 12 o'clock position. Currently they start at the 3 o'clock position.
![screen shot 2016-07-17 at 20 49 57](https://cloud.githubusercontent.com/assets/8081877/16902755/17a8c75c-4c60-11e6-9901-f4ed2ca55f4c.png)

**Comment by camjc** [comment]
I guess 12 should be the default, it reads better. Could either use an svg rotate or change the maths bit. Open to a pull request if you've got time :)

**Comment by ghost** [comment]
Great! Thanks!
